version: "3"

networks:
  reverse_proxy:
    external: true

services:
  markdownpleasecom_static:
    build: .
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=markdownplease.com
      - LETSENCRYPT_HOST=markdownplease.com
      - LETSENCRYPT_EMAIL=zymen@zymen.net
    networks:
      - default
      - reverse_proxy
